//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOT.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string BtnGallery {
            get {
                return ResourceManager.GetString("BtnGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel.
        /// </summary>
        public static string BtnIntel {
            get {
                return ResourceManager.GetString("BtnIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possesses near-superhuman reflexes due to awakened Ackerman bloodlines. Unmatched with vertical maneuvering equipment, universally hailed as Humanity&apos;s Strongest..
        /// </summary>
        public static string C1Bio {
            get {
                return ResourceManager.GetString("C1Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levi Ackerman.
        /// </summary>
        public static string C1Name {
            get {
                return ResourceManager.GetString("C1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Operations Captain.
        /// </summary>
        public static string C1Title {
            get {
                return ResourceManager.GetString("C1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to a hundred ordinary soldiers in combat. Graduated from the 104th Training Corps alongside Eren, driven by an absolute, singular drive to protect him at all costs..
        /// </summary>
        public static string C2Bio {
            get {
                return ResourceManager.GetString("C2Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikasa Ackerman.
        /// </summary>
        public static string C2Name {
            get {
                return ResourceManager.GetString("C2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Scout Officer.
        /// </summary>
        public static string C2Title {
            get {
                return ResourceManager.GetString("C2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eren and Mikasa&apos;s childhood friend. Possesses an extraordinary tactical mind, devising brilliant counter-strategies in dire situations. Inherited the Colossal Titan..
        /// </summary>
        public static string C3Bio {
            get {
                return ResourceManager.GetString("C3Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armin Arlert.
        /// </summary>
        public static string C3Name {
            get {
                return ResourceManager.GetString("C3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15th Scout Commander / Colossal Titan.
        /// </summary>
        public static string C3Title {
            get {
                return ResourceManager.GetString("C3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Led the Scout Corps&apos; scientific research and weapon development, notably creating the Thunder Spears. Succeeded Erwin as the 14th Commander with high integrity..
        /// </summary>
        public static string C4Bio {
            get {
                return ResourceManager.GetString("C4Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hange Zoë.
        /// </summary>
        public static string C4Name {
            get {
                return ResourceManager.GetString("C4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14th Scout Commander.
        /// </summary>
        public static string C4Title {
            get {
                return ResourceManager.GetString("C4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A legendary leader with frozen resolve and hypnotic charisma. Developed the Long-Distance Scouting Formation. Sacrificed himself to historical truth..
        /// </summary>
        public static string C5Bio {
            get {
                return ResourceManager.GetString("C5Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwin Smith.
        /// </summary>
        public static string C5Name {
            get {
                return ResourceManager.GetString("C5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Former 13th Scout Commander.
        /// </summary>
        public static string C5Title {
            get {
                return ResourceManager.GetString("C5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A grounded realist who understands weakness, enabling him to assess battlefields accurately from a soldier&apos;s view. Became a highly trusted field commander..
        /// </summary>
        public static string C6Bio {
            get {
                return ResourceManager.GetString("C6Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jean Kirstein.
        /// </summary>
        public static string C6Name {
            get {
                return ResourceManager.GetString("C6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline Field Commander.
        /// </summary>
        public static string C6Title {
            get {
                return ResourceManager.GetString("C6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marleyan Reform Faction.
        /// </summary>
        public static string FactionBtn1 {
            get {
                return ResourceManager.GetString("FactionBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paradis Alliance Faction.
        /// </summary>
        public static string FactionBtn2 {
            get {
                return ResourceManager.GetString("FactionBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do your priorities reside in the final conflict?.
        /// </summary>
        public static string FactionDesc {
            get {
                return ResourceManager.GetString("FactionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Alignment.
        /// </summary>
        public static string FactionTitle {
            get {
                return ResourceManager.GetString("FactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 Created by kockhwie. All rights reserved..
        /// </summary>
        public static string FooterCredit {
            get {
                return ResourceManager.GetString("FooterCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A revolutionary invention enabling humanity to fight titans. Utilizes high-pressure gas cylinders and steel wire anchors to allow high-speed 3D mobility through trees and urban structures..
        /// </summary>
        public static string G1Desc {
            get {
                return ResourceManager.GetString("G1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omni-directional Mobility Gear.
        /// </summary>
        public static string G1Name {
            get {
                return ResourceManager.GetString("G1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech: Gas-Powered Pneumatic Winch System.
        /// </summary>
        public static string G1Tech {
            get {
                return ResourceManager.GetString("G1Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard-issue melee cutlery forged from industrial black-bamboo alloy. Engineered for high flexibility and razor sharpness to slice titan flesh. Features an instant segment-reload design..
        /// </summary>
        public static string G2Desc {
            get {
                return ResourceManager.GetString("G2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultrahard Steel Blades.
        /// </summary>
        public static string G2Name {
            get {
                return ResourceManager.GetString("G2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech: Industrial Black-Bamboo Alloy.
        /// </summary>
        public static string G2Tech {
            get {
                return ResourceManager.GetString("G2Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specialized heavy anti-titan armor-piercing rocket weapon developed by Hange. Anchors directly into target frameworks and detonates via a tethered cord, strong enough to shatter hardened skin armor..
        /// </summary>
        public static string G3Desc {
            get {
                return ResourceManager.GetString("G3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder Spears.
        /// </summary>
        public static string G3Name {
            get {
                return ResourceManager.GetString("G3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech: Jet-Propelled High-Explosive Ordnance.
        /// </summary>
        public static string G3Tech {
            get {
                return ResourceManager.GetString("G3Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Gear &amp; Scout Ordnance.
        /// </summary>
        public static string GearSectionTitle {
            get {
                return ResourceManager.GetString("GearSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the elite warriors of Paradis and Marley in this comprehensive database. Track their abilities, affiliations, and crucial combat data in the ongoing conflict..
        /// </summary>
        public static string HeroDesc {
            get {
                return ResourceManager.GetString("HeroDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURVEY CORPS INTEL.
        /// </summary>
        public static string HeroTag {
            get {
                return ResourceManager.GetString("HeroTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack on Titan Character Database.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possesses near-superhuman reflexes due to awakened Ackerman bloodlines. Lethal with vertical maneuvering equipment..
        /// </summary>
        public static string LeviBio {
            get {
                return ResourceManager.GetString("LeviBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levi Ackerman.
        /// </summary>
        public static string LeviName {
            get {
                return ResourceManager.GetString("LeviName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Operations Captain.
        /// </summary>
        public static string LeviTitle {
            get {
                return ResourceManager.GetString("LeviTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to a hundred ordinary soldiers in combat. Driven by an absolute, singular drive to protect Eren Yeager at all costs..
        /// </summary>
        public static string MikasaBio {
            get {
                return ResourceManager.GetString("MikasaBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikasa Ackerman.
        /// </summary>
        public static string MikasaName {
            get {
                return ResourceManager.GetString("MikasaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Scout Officer.
        /// </summary>
        public static string MikasaTitle {
            get {
                return ResourceManager.GetString("MikasaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 9 Titans -.
        /// </summary>
        public static string Nav_9Titans9 {
            get {
                return ResourceManager.GetString("Nav_9Titans9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Author Hajime Isayama.
        /// </summary>
        public static string Nav_AboutAuthorHajimeIsayama {
            get {
                return ResourceManager.GetString("Nav_AboutAuthorHajimeIsayama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - All Members -.
        /// </summary>
        public static string Nav_AllMembers {
            get {
                return ResourceManager.GetString("Nav_AllMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string Nav_Anime {
            get {
                return ResourceManager.GetString("Nav_Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annie Leonhart.
        /// </summary>
        public static string Nav_AnnieLeonhart {
            get {
                return ResourceManager.GetString("Nav_AnnieLeonhart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armin.
        /// </summary>
        public static string Nav_Armin {
            get {
                return ResourceManager.GetString("Nav_Armin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armored Titan.
        /// </summary>
        public static string Nav_ArmoredTitan {
            get {
                return ResourceManager.GetString("Nav_ArmoredTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Titan.
        /// </summary>
        public static string Nav_AttackTitan {
            get {
                return ResourceManager.GetString("Nav_AttackTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurille.
        /// </summary>
        public static string Nav_Aurille {
            get {
                return ResourceManager.GetString("Nav_Aurille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast Titan.
        /// </summary>
        public static string Nav_BeastTitan {
            get {
                return ResourceManager.GetString("Nav_BeastTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bertolt Hoover.
        /// </summary>
        public static string Nav_BertoltHoover {
            get {
                return ResourceManager.GetString("Nav_BertoltHoover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Nav_Books {
            get {
                return ResourceManager.GetString("Nav_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boris Feulner.
        /// </summary>
        public static string Nav_BorisFeulner {
            get {
                return ResourceManager.GetString("Nav_BorisFeulner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calvi - The Marshal.
        /// </summary>
        public static string Nav_CalviTheMarshal {
            get {
                return ResourceManager.GetString("Nav_CalviTheMarshal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Captains -.
        /// </summary>
        public static string Nav_Captains {
            get {
                return ResourceManager.GetString("Nav_Captains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carla Yeager.
        /// </summary>
        public static string Nav_CarlaYeager {
            get {
                return ResourceManager.GetString("Nav_CarlaYeager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Titan.
        /// </summary>
        public static string Nav_CartTitan {
            get {
                return ResourceManager.GetString("Nav_CartTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilians.
        /// </summary>
        public static string Nav_Civilians {
            get {
                return ResourceManager.GetString("Nav_Civilians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossal Titan.
        /// </summary>
        public static string Nav_ColossalTitan {
            get {
                return ResourceManager.GetString("Nav_ColossalTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colt Grice.
        /// </summary>
        public static string Nav_ColtGrice {
            get {
                return ResourceManager.GetString("Nav_ColtGrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics.
        /// </summary>
        public static string Nav_Comics {
            get {
                return ResourceManager.GetString("Nav_Comics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Commanders -.
        /// </summary>
        public static string Nav_Commanders {
            get {
                return ResourceManager.GetString("Nav_Commanders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltoff.
        /// </summary>
        public static string Nav_Deltoff {
            get {
                return ResourceManager.GetString("Nav_Deltoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimo Reeves.
        /// </summary>
        public static string Nav_DimoReeves {
            get {
                return ResourceManager.GetString("Nav_DimoReeves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djel Sannes.
        /// </summary>
        public static string Nav_DjelSanes {
            get {
                return ResourceManager.GetString("Nav_DjelSanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Pixis.
        /// </summary>
        public static string Nav_DotPixis {
            get {
                return ResourceManager.GetString("Nav_DotPixis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eld Jinn.
        /// </summary>
        public static string Nav_EldJinn {
            get {
                return ResourceManager.GetString("Nav_EldJinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eren Yeager.
        /// </summary>
        public static string Nav_Eren {
            get {
                return ResourceManager.GetString("Nav_Eren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwin Smith.
        /// </summary>
        public static string Nav_ErwinSmith {
            get {
                return ResourceManager.GetString("Nav_ErwinSmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falco Grice.
        /// </summary>
        public static string Nav_FalcoGrice {
            get {
                return ResourceManager.GetString("Nav_FalcoGrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan arts.
        /// </summary>
        public static string Nav_Fanarts {
            get {
                return ResourceManager.GetString("Nav_Fanarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Titan.
        /// </summary>
        public static string Nav_FemaleTitan {
            get {
                return ResourceManager.GetString("Nav_FemaleTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floch Forster.
        /// </summary>
        public static string Nav_FlochForster {
            get {
                return ResourceManager.GetString("Nav_FlochForster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founding Titan.
        /// </summary>
        public static string Nav_FoundingTitan {
            get {
                return ResourceManager.GetString("Nav_FoundingTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frieda Reiss.
        /// </summary>
        public static string Nav_FriedaReiss {
            get {
                return ResourceManager.GetString("Nav_FriedaReiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fritz.
        /// </summary>
        public static string Nav_Fritz {
            get {
                return ResourceManager.GetString("Nav_Fritz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabi Braun.
        /// </summary>
        public static string Nav_GabiBraun {
            get {
                return ResourceManager.GetString("Nav_GabiBraun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Nav_Gallery {
            get {
                return ResourceManager.GetString("Nav_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Nav_Games {
            get {
                return ResourceManager.GetString("Nav_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garrison Regiment.
        /// </summary>
        public static string Nav_GarrisonRegiment {
            get {
                return ResourceManager.GetString("Nav_GarrisonRegiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerald.
        /// </summary>
        public static string Nav_Gerald {
            get {
                return ResourceManager.GetString("Nav_Gerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günther Schultz.
        /// </summary>
        public static string Nav_GntherSchultz {
            get {
                return ResourceManager.GetString("Nav_GntherSchultz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grisha Yeager.
        /// </summary>
        public static string Nav_GrishaYeager {
            get {
                return ResourceManager.GetString("Nav_GrishaYeager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hange Zoë.
        /// </summary>
        public static string Nav_HangeZoe {
            get {
                return ResourceManager.GetString("Nav_HangeZoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hannes.
        /// </summary>
        public static string Nav_Hannes {
            get {
                return ResourceManager.GetString("Nav_Hannes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string Nav_Historia {
            get {
                return ResourceManager.GetString("Nav_Historia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitch Dreyse.
        /// </summary>
        public static string Nav_HitchDreyse {
            get {
                return ResourceManager.GetString("Nav_HitchDreyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Titan.
        /// </summary>
        public static string Nav_JawTitan {
            get {
                return ResourceManager.GetString("Nav_JawTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaya.
        /// </summary>
        public static string Nav_Kaya {
            get {
                return ResourceManager.GetString("Nav_Kaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenny Ackerman.
        /// </summary>
        public static string Nav_KennyAckerman {
            get {
                return ResourceManager.GetString("Nav_KennyAckerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lara Tybur.
        /// </summary>
        public static string Nav_LaraTybur {
            get {
                return ResourceManager.GetString("Nav_LaraTybur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levi Ackerman.
        /// </summary>
        public static string Nav_LeviAckerman {
            get {
                return ResourceManager.GetString("Nav_LeviAckerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string Nav_Magazines {
            get {
                return ResourceManager.GetString("Nav_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Nav_Main {
            get {
                return ResourceManager.GetString("Nav_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga.
        /// </summary>
        public static string Nav_Manga {
            get {
                return ResourceManager.GetString("Nav_Manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcel Galliard.
        /// </summary>
        public static string Nav_MarcelGalliard {
            get {
                return ResourceManager.GetString("Nav_MarcelGalliard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marley.
        /// </summary>
        public static string Nav_Marley {
            get {
                return ResourceManager.GetString("Nav_Marley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marlowe Freudenberg.
        /// </summary>
        public static string Nav_MarloweFreudenberg {
            get {
                return ResourceManager.GetString("Nav_MarloweFreudenberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikasa Ackerman.
        /// </summary>
        public static string Nav_Mikasa {
            get {
                return ResourceManager.GetString("Nav_Mikasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Police Brigade.
        /// </summary>
        public static string Nav_MilitaryPoliceBrigade {
            get {
                return ResourceManager.GetString("Nav_MilitaryPoliceBrigade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister Nick.
        /// </summary>
        public static string Nav_MinisterNick {
            get {
                return ResourceManager.GetString("Nav_MinisterNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Nav_Movies {
            get {
                return ResourceManager.GetString("Nav_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nile Dok.
        /// </summary>
        public static string Nav_NileDok {
            get {
                return ResourceManager.GetString("Nav_NileDok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluo Bozado.
        /// </summary>
        public static string Nav_OluoBozado {
            get {
                return ResourceManager.GetString("Nav_OluoBozado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Nav_Other {
            get {
                return ResourceManager.GetString("Nav_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Others -.
        /// </summary>
        public static string Nav_Others {
            get {
                return ResourceManager.GetString("Nav_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petra Ral.
        /// </summary>
        public static string Nav_PetraRal {
            get {
                return ResourceManager.GetString("Nav_PetraRal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieck Finger.
        /// </summary>
        public static string Nav_PieckFinger {
            get {
                return ResourceManager.GetString("Nav_PieckFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porco Galliard.
        /// </summary>
        public static string Nav_PorcoGalliard {
            get {
                return ResourceManager.GetString("Nav_PorcoGalliard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Nav_Quotes {
            get {
                return ResourceManager.GetString("Nav_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiner Braun.
        /// </summary>
        public static string Nav_ReinerBraun {
            get {
                return ResourceManager.GetString("Nav_ReinerBraun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rico Brzenska.
        /// </summary>
        public static string Nav_RicoBrzenska {
            get {
                return ResourceManager.GetString("Nav_RicoBrzenska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roderich.
        /// </summary>
        public static string Nav_Roderich {
            get {
                return ResourceManager.GetString("Nav_Roderich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rod Reiss.
        /// </summary>
        public static string Nav_RodReiss {
            get {
                return ResourceManager.GetString("Nav_RodReiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruling Family.
        /// </summary>
        public static string Nav_RulingFamily {
            get {
                return ResourceManager.GetString("Nav_RulingFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Commander.
        /// </summary>
        public static string Nav_SectionCommander {
            get {
                return ResourceManager.GetString("Nav_SectionCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonny and Bean.
        /// </summary>
        public static string Nav_SonnyandBean {
            get {
                return ResourceManager.GetString("Nav_SonnyandBean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Nav_Statistics {
            get {
                return ResourceManager.GetString("Nav_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Nav_Story {
            get {
                return ResourceManager.GetString("Nav_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Corps.
        /// </summary>
        public static string Nav_SurveyCorps {
            get {
                return ResourceManager.GetString("Nav_SurveyCorps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Anti-Marleyan Volunteers.
        /// </summary>
        public static string Nav_TheAntiMarleyanVolunteers {
            get {
                return ResourceManager.GetString("Nav_TheAntiMarleyanVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Interior Squad.
        /// </summary>
        public static string Nav_TheFirstInteriorSquad {
            get {
                return ResourceManager.GetString("Nav_TheFirstInteriorSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Magath - A commander.
        /// </summary>
        public static string Nav_TheoMagathAcommander {
            get {
                return ResourceManager.GetString("Nav_TheoMagathAcommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Royal Government .
        /// </summary>
        public static string Nav_TheRoyalGovernment {
            get {
                return ResourceManager.GetString("Nav_TheRoyalGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Survey Corps Special Operations Squad.
        /// </summary>
        public static string Nav_TheSurveyCorpsSpecialOperation {
            get {
                return ResourceManager.GetString("Nav_TheSurveyCorpsSpecialOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Nav_Timeline {
            get {
                return ResourceManager.GetString("Nav_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titans.
        /// </summary>
        public static string Nav_Titans {
            get {
                return ResourceManager.GetString("Nav_Titans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traute Carven.
        /// </summary>
        public static string Nav_TrauteCarven {
            get {
                return ResourceManager.GetString("Nav_TrauteCarven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tybur Family.
        /// </summary>
        public static string Nav_TyburFamily {
            get {
                return ResourceManager.GetString("Nav_TyburFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underground.
        /// </summary>
        public static string Nav_Underground {
            get {
                return ResourceManager.GetString("Nav_Underground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Titans.
        /// </summary>
        public static string Nav_WallTitans {
            get {
                return ResourceManager.GetString("Nav_WallTitans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War Hammer Titan.
        /// </summary>
        public static string Nav_WarHammerTitan {
            get {
                return ResourceManager.GetString("Nav_WarHammerTitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Warrior Unit -.
        /// </summary>
        public static string Nav_WarriorUnit {
            get {
                return ResourceManager.GetString("Nav_WarriorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willy Tybur.
        /// </summary>
        public static string Nav_WillyTybur {
            get {
                return ResourceManager.GetString("Nav_WillyTybur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeagerists.
        /// </summary>
        public static string Nav_Yeagerists {
            get {
                return ResourceManager.GetString("Nav_Yeagerists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeke Yeager.
        /// </summary>
        public static string Nav_ZekeYeager {
            get {
                return ResourceManager.GetString("Nav_ZekeYeager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string NavCharacters {
            get {
                return ResourceManager.GetString("NavCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string NavExplore {
            get {
                return ResourceManager.GetString("NavExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Zone.
        /// </summary>
        public static string NavFanZone {
            get {
                return ResourceManager.GetString("NavFanZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lore &amp; Maps.
        /// </summary>
        public static string NavLoreMaps {
            get {
                return ResourceManager.GetString("NavLoreMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string NavMedia {
            get {
                return ResourceManager.GetString("NavMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NavNews {
            get {
                return ResourceManager.GetString("NavNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardening &amp; Magic.
        /// </summary>
        public static string ParamArmor {
            get {
                return ResourceManager.GetString("ParamArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructive Power.
        /// </summary>
        public static string ParamPower {
            get {
                return ResourceManager.GetString("ParamPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility &amp; Speed.
        /// </summary>
        public static string ParamSpeed {
            get {
                return ResourceManager.GetString("ParamSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Members of the Survey Corps.
        /// </summary>
        public static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Database.
        /// </summary>
        public static string SidebarBtn {
            get {
                return ResourceManager.GetString("SidebarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized connection online. Accessing cryptographic communication records and wall structural safety data paths..
        /// </summary>
        public static string SidebarDesc {
            get {
                return ResourceManager.GetString("SidebarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Terminal.
        /// </summary>
        public static string SidebarTitle {
            get {
                return ResourceManager.GetString("SidebarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Risk.
        /// </summary>
        public static string SpecRisk {
            get {
                return ResourceManager.GetString("SpecRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Weight.
        /// </summary>
        public static string SpecWeight {
            get {
                return ResourceManager.GetString("SpecWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Kills.
        /// </summary>
        public static string StatKills {
            get {
                return ResourceManager.GetString("StatKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wits Value.
        /// </summary>
        public static string StatWits {
            get {
                return ResourceManager.GetString("StatWits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nexus of all titans. Wields the ultimate &apos;Coordinate&apos; ability to alter memories and command millions of Wall Titans to initiate the Cataclysmic &apos;Rumbling&apos;..
        /// </summary>
        public static string T1Desc {
            get {
                return ResourceManager.GetString("T1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 13m (Base Form).
        /// </summary>
        public static string T1H {
            get {
                return ResourceManager.GetString("T1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founding Titan.
        /// </summary>
        public static string T1Name {
            get {
                return ResourceManager.GetString("T1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possessed by Annie Leonhart. Exhibits high all-around agility, specialized localized crystalline hardening defenses, and a vocal call that summons pure titans..
        /// </summary>
        public static string T2Desc {
            get {
                return ResourceManager.GetString("T2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 14m.
        /// </summary>
        public static string T2H {
            get {
                return ResourceManager.GetString("T2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Titan.
        /// </summary>
        public static string T2Name {
            get {
                return ResourceManager.GetString("T2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held by Zeke Yeager. Resembles an ape-like beast capable of devastating long-range bombardment. Due to royal blood, his spinal fluid instantly transforms targets..
        /// </summary>
        public static string T3Desc {
            get {
                return ResourceManager.GetString("T3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 17m.
        /// </summary>
        public static string T3H {
            get {
                return ResourceManager.GetString("T3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast Titan.
        /// </summary>
        public static string T3Name {
            get {
                return ResourceManager.GetString("T3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held by Bertholdt, then Armin. Possesses a mountainous structure. Transformation triggers a pseudo-nuclear thermal blast, alongside a tactical high-pressure burning steam defensive barrier..
        /// </summary>
        public static string T4Desc {
            get {
                return ResourceManager.GetString("T4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 60m.
        /// </summary>
        public static string T4H {
            get {
                return ResourceManager.GetString("T4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colossal Titan.
        /// </summary>
        public static string T4Name {
            get {
                return ResourceManager.GetString("T4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held by Reiner Braun. Encased in a heavy hardened skeletal armor plating that provides fortress-grade defensive metrics. Functions as an organic battering ram against fortified structures..
        /// </summary>
        public static string T5Desc {
            get {
                return ResourceManager.GetString("T5Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 15m.
        /// </summary>
        public static string T5H {
            get {
                return ResourceManager.GetString("T5H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armored Titan.
        /// </summary>
        public static string T5Name {
            get {
                return ResourceManager.GetString("T5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held by Ymir, Falco, and others. The smallest form but unmatched in top-tier agility. Features powerful claws and jaws that can crush even the densest crystalline hardening..
        /// </summary>
        public static string T6Desc {
            get {
                return ResourceManager.GetString("T6Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 5m.
        /// </summary>
        public static string T6H {
            get {
                return ResourceManager.GetString("T6H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Titan.
        /// </summary>
        public static string T6Name {
            get {
                return ResourceManager.GetString("T6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held by Pieck Finger. Utilizes a quadrupedal stance with unparalleled physiological endurance, allowing months of sustained transformation. Can be equipped with customized heavy military artillery..
        /// </summary>
        public static string T7Desc {
            get {
                return ResourceManager.GetString("T7Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 4m (Quadrupedal).
        /// </summary>
        public static string T7H {
            get {
                return ResourceManager.GetString("T7H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Titan.
        /// </summary>
        public static string T7Name {
            get {
                return ResourceManager.GetString("T7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originally held by the Tybur family. Features absolute weapon materialization via dense structural hardening. The host can safely remain underground while managing the titan puppet remotely via a cable connection..
        /// </summary>
        public static string T8Desc {
            get {
                return ResourceManager.GetString("T8Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 15m.
        /// </summary>
        public static string T8H {
            get {
                return ResourceManager.GetString("T8H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War Hammer Titan.
        /// </summary>
        public static string T8Name {
            get {
                return ResourceManager.GetString("T8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The core combat avatar managed by Eren Yeager. Features balanced combat stats, flawless tactical grit, and the unique cross-temporal memory foresight capability..
        /// </summary>
        public static string T9Desc {
            get {
                return ResourceManager.GetString("T9Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: 15m.
        /// </summary>
        public static string T9H {
            get {
                return ResourceManager.GetString("T9H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attack Titan (Host).
        /// </summary>
        public static string T9Name {
            get {
                return ResourceManager.GetString("T9Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Colossal and Armored Titans breached Wall Maria, ending a century of fragile human peace..
        /// </summary>
        public static string Time1Desc {
            get {
                return ResourceManager.GetString("Time1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall of Shiganshina District.
        /// </summary>
        public static string Time1Title {
            get {
                return ResourceManager.GetString("Time1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eren Yeager launched a surprise raid on Liberio, shifting the global war into its endgame..
        /// </summary>
        public static string Time2Desc {
            get {
                return ResourceManager.GetString("Time2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Declaration of War.
        /// </summary>
        public static string Time2Title {
            get {
                return ResourceManager.GetString("Time2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical War Chronicle.
        /// </summary>
        public static string TimelineHeader {
            get {
                return ResourceManager.GetString("TimelineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nine Titans Registry.
        /// </summary>
        public static string TitanSectionTitle {
            get {
                return ResourceManager.GetString("TitanSectionTitle", resourceCulture);
            }
        }
    }
}
